import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Header } from "@/components/shared/header";

const schoolbell = localFont({
  src: "../font/Schoolbell.ttf.woff",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Zametoshka",
  description: "Generated by Sahara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${schoolbell.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="min-h-screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
