import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { BrowserShell, Header } from "@/components/shared";

const schoolbell = localFont({
  src: "../font/Schoolbell.ttf.woff",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Zametoshka",
  description: "Generated by Sahara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${schoolbell.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#d8cbb8]">
        <BrowserShell>
          <main className="min-h-screen">
            <Header />
            {children}
          </main>
        </BrowserShell>
      </body>
    </html>
  );
}
